# Generated by Django 4.1.7 on 2023-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
