# Generated by Django 4.2.4 on 2023-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_visit_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='sku',
            field=models.ManyToManyField(blank=True, to='store.sku'),
        ),
    ]
